### ISSUE TITLE
Ignorar paths do backend no workflow de CI do frontend

### ISSUE THREAD

**Issue by crysisprophet1234** [crysisprophet1234/poletto-skins#16]
Ignorar paths do backend no workflow de CI do frontend, seguindo o exemplo do workflow de CD:

```yml
on:
  push:
    branches: ["main"]
    paths-ignore: ["/backend"]
```
